name: CSS Presubmit

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install npm packages
        run: npm install
      - name: Lint
        run: npx stylelint "capstone/client/src/components/*.css"
